name: contacts_demo
description: Contacts App Demo
homepage: https://www.andrioussolutions.com
repository: https://github.com/Andrious/contacts_demo
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:

  # https://pub.dev/packages/auth
  auth: 8.2.0+02 #^8.0.0

  cupertino_icons: 1.0.5 #^1.0.2

  # https://pub.dev/packages/dbutils
  dbutils: 6.0.0 #^6.0.0

  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: ^3.3.0 #3.0.15 #^3.0.0

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_material_color_picker/
  flutter_material_color_picker: 1.1.0+2 #^1.0.0

  # https://pub.dev/packages/fluttery_framework
  fluttery_framework: ^3.1.0
#    path: ../../packages/fluttery_framework

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  # Used during Continuous Integration
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/sunny.png
    - assets/images/moon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
