// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl55U4Nwr7SYJaSOOaJHuWVgh4i9Z27jY',
    appId: '1:255669178085:web:cfdcdecf105f1f848e4e0c',
    messagingSenderId: '255669178085',
    projectId: 'project-for-examples',
    authDomain: 'project-for-examples.firebaseapp.com',
    storageBucket: 'project-for-examples.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZZdtCwt8nvzrgjK7AdlWLJzYeL34ek4',
    appId: '1:255669178085:android:bc9101fdc975e96d8e4e0c',
    messagingSenderId: '255669178085',
    projectId: 'project-for-examples',
    storageBucket: 'project-for-examples.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzjtYpgtZZRfcAFyx1bxHYJKrPDhnia20',
    appId: '1:255669178085:ios:570cfddc51422a008e4e0c',
    messagingSenderId: '255669178085',
    projectId: 'project-for-examples',
    storageBucket: 'project-for-examples.appspot.com',
    androidClientId: '255669178085-sgrf4fg6hepb2c8qhhd72fsl1297tiuu.apps.googleusercontent.com',
    iosClientId: '255669178085-a1brkaf5sl610appu1sp7r4hs4dp9jcb.apps.googleusercontent.com',
    iosBundleId: 'com.andrioussolutions.contactsDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzjtYpgtZZRfcAFyx1bxHYJKrPDhnia20',
    appId: '1:255669178085:ios:570cfddc51422a008e4e0c',
    messagingSenderId: '255669178085',
    projectId: 'project-for-examples',
    storageBucket: 'project-for-examples.appspot.com',
    androidClientId: '255669178085-sgrf4fg6hepb2c8qhhd72fsl1297tiuu.apps.googleusercontent.com',
    iosClientId: '255669178085-a1brkaf5sl610appu1sp7r4hs4dp9jcb.apps.googleusercontent.com',
    iosBundleId: 'com.andrioussolutions.contactsDemo',
  );
}
